// Interface strings for src/lib/i18n.js. Keep both dictionaries in the same key
// order; tests/unit/i18n.test.js checks that every English key has a Spanish one
// and that the placeholders match.

export const STRINGS_EN = {
  // App shell (index.html)
  'app.title': 'LvPrime · Coach workspace',
  'app.logoLabel': 'LvPrime, go to overview',
  'app.subtitle': 'Personal training · 40+',
  'app.workspace': 'Coach workspace',
  'app.sidebarLabel': 'Clients',
  'lang.groupLabel': 'Language',
  'lang.es': 'Español',
  'lang.en': 'English',

  // Shared
  'common.allClients': 'All clients',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.saving': 'Saving…',
  'common.date': 'Date',
  'common.required': 'required',
  'common.saved': 'Saved',
  'common.downloadPdf': 'Download PDF',
  'common.pdfFailed': 'Could not generate the PDF. Please try again.',
  'common.refreshFailed': 'Saved, but the page could not refresh. Reload to see it.',
  'common.couldNotSave': 'Could not save. Try again.',

  // Status and relative dates
  'status.no-feedback': 'No feedback',
  'status.needs-checkin': 'Needs check-in',
  'status.on-track': 'On track',
  'rel.never': 'Never',
  'rel.today': 'Today',
  'rel.yesterday': 'Yesterday',
  'rel.daysAgo': '{n}d ago',

  // Overview
  'overview.title': 'Clients',
  'overview.searchPlaceholder': 'Search by name',
  'overview.searchLabel': 'Search clients',
  'overview.loadFailed': 'Failed to load clients.',
  'overview.empty': 'Add your first client to start building their program.',
  'overview.count.one': '{n} client',
  'overview.count.other': '{n} clients',
  'overview.showing': 'Showing {visible} of {total} clients',
  'overview.noFlagged': 'No client has a pain or "brutal" flag in their last sessions.',
  'overview.noMatch': 'No clients match "{query}".',
  'overview.noMatchIn': 'No clients match "{query}" under {filter}.',
  'overview.noneIn': 'No clients under {filter} right now.',
  'overview.showAll': 'Show all clients',
  'score.clients': 'Clients',
  'score.needCheckin': 'Need a check-in',
  'score.onTrack': 'On track',
  'score.noFeedback': 'No feedback yet',
  'filter.groupLabel': 'Filter clients',
  'filter.all': 'All',
  'filter.needs-checkin': 'Needs check-in',
  'filter.flagged': 'Flagged',
  'filter.week-due': 'New week due',
  'filter.no-feedback': 'No feedback yet',
  'filter.archived': 'Archived',

  // Client card
  'card.pain': 'Pain {level}/10',
  'card.mentionsPain': 'Mentions pain',
  'card.brutal': 'Session felt brutal',
  'card.week': 'Week {n}',
  'card.weekDue': '{week} is {days}d old · new week due',
  'card.adherencePercent': '{percent}% done · {done}/{total} in {days}d',
  'card.adherenceLogged': '{n} logged · {days}d',
  'card.adherenceNone': 'No sessions in {days}d',
  'card.programInProgress': 'Program in progress',
  'card.noProgram': 'No program yet',
  'card.checkIn': 'Check-in {when}',
  'card.noCheckIn': 'No check-in yet',
  'card.archived': 'Archived',

  // Client page
  'customer.loadFailed': 'Failed to load this customer.',
  'tabs.program': 'Program',
  'tabs.nutrition': 'Nutrition Plan',
  'tabs.feedback': 'Feedback',
  'tabs.progress': 'Progress',
  'tabs.add-entry': 'Log Session',
  'tabs.notes': 'Notes',
  'difficulty.1': 'Easy',
  'difficulty.2': 'Moderate',
  'difficulty.3': 'Hard',
  'difficulty.4': 'Brutal',
  'toast.measurementsSaved': 'Measurements saved',
  'toast.feedbackSaved': 'Saved · view in Feedback',
  'toast.sessionLogged': 'Session logged',
  'hero.lastCheckIn': 'Last check-in {when}',
  'hero.weekOf': 'Week {current} of {total}',
  'hero.level': 'Level',
  'hero.session': 'Session',
  'hero.plan': 'Plan',

  // Archive
  'archive.button': 'Archive client',
  'archive.restore': 'Restore client',
  'archive.confirm': 'Archive {name}? They will be hidden from the client list and sidebar. You can restore them anytime from the Archived filter.',
  'archive.banner': 'Archived on {date}. This client is hidden from the client list.',
  'archive.done': 'Client archived',
  'archive.restored': 'Client restored',
  'archive.failed': 'Could not update the client. Try again.',

  // Attachments
  'attach.title': 'Attachments',
  'attach.upload': 'Attach file',
  'attach.uploading': 'Uploading…',
  'attach.uploaded': 'File attached',
  'attach.remove': 'Remove {name}',
  'attach.confirmRemove': 'Remove "{name}"? This deletes the file.',
  'attach.removed': 'File removed',
  'attach.empty': 'No files yet. PDFs, images, Word and Excel files up to {mb} MB.',
  'attach.unavailable': 'Attachments can\'t be loaded right now.',
  'attach.tooLarge': 'Files must be {mb} MB or smaller.',
  'attach.badType': 'Only PDF, image, text, Word and Excel files can be attached.',
  'attach.failed': 'Could not upload the file. Try again.',
  'attach.removeFailed': 'Could not remove the file. Try again.',

  // Program tab
  'week.navLabel': 'Program week',
  'week.chip': 'Week {n}',
  'week.lockedTitle': 'Past week (read-only)',
  'week.lockedLabel': 'Week {n}, past week, read-only',
  'program.empty': 'No program yet.',
  'program.createWeek1': 'Create week 1',
  'program.week1Title': 'Week 1 program',
  'program.loadWeekFailed': 'Could not load week {n}. Please try again.',
  'program.editWeek': 'Edit week',
  'program.editWeekTitle': 'Edit week {n}',
  'program.newWeek': 'New week',
  'program.newWeekTitle': 'New week {n}',
  'program.pastWeek': 'Week {n} · past week, read-only',
  'program.noSchedule': 'No schedule for this week.',
  'day.navLabel': 'Program days',
  'day.watchVideo': '{name}, watch demo video',
  'day.rest': 'Rest {rest}',
  'day.doneToday': 'Done today',
  'day.doneOn': 'Done {date}',
  'day.addDetails': 'Add details',
  'day.editDetails': 'Edit details',
  'day.notes.title': 'Session details',
  'day.notes.hint': 'One note for the whole session. Fill in each exercise with your weights, reps or how it felt, and edit it any time. You can save it before marking the day done.',
  'day.markDone': 'Mark done',
  'day.exercises.one': '{n} exercise',
  'day.exercises.other': '{n} exercises',

  // Feedback tab
  'feedback.trend': 'Session trend',
  'feedback.history': 'Session history',
  'feedback.empty': 'No sessions logged yet. Log a session to start tracking feedback.',
  'stats.completion': 'Completion',
  'stats.lastSession': 'Last session',
  'stats.avgDifficulty': 'Avg. difficulty',
  'stats.notEnough': 'Not enough data yet',
  'entry.undated': 'Undated session',
  'entry.completed': 'Completed',
  'entry.notCompleted': 'Not completed',
  'entry.felt': 'Felt',
  'entry.difficulty': 'Difficulty',
  'trend.aria': 'Difficulty and completion trend over sessions',
  'trend.notEnough': 'Not enough feedback yet to show a trend.',
  'trend.unknownDate': 'Unknown date',
  'trend.point': '{date}: {state}, {difficulty}',
  'trend.pointDifficulty': 'difficulty {score}/{max}',
  'trend.noDifficulty': 'no difficulty recorded',
  'trend.completed': 'Completed',
  'trend.missed': 'Missed',
  'trend.note': 'Bar height shows difficulty. Bars grow once difficulty is logged as Easy, Moderate, Hard or Brutal (or Fácil, Moderada, Difícil).',

  // Log Session tab
  'logForm.title': 'Log a new session',
  'logForm.intro': 'Only Completed is required; leave the rest blank if unknown. Saved entries appear under Feedback, newest first.',
  'logForm.label': 'Session label (optional)',
  'logForm.labelPlaceholder': 'e.g. Lunes - Piernas A',
  'logForm.select': 'Select…',
  'logForm.skip': '—',
  // Labels for the English field names in older feedback.md templates (feedback-fields.js).
  'logField.energy level': 'Energy level',
  'logField.completed': 'Completed',
  'logField.exercises completed': 'Exercises completed',
  'logField.how felt': 'How it felt',
  'logField.how customer felt': 'How it felt',
  'logField.elbow status': 'Elbow status',
  'logField.notes': 'Notes',
  'logField.overall impression': 'Overall impression',
  'logForm.yes': 'Yes',
  'logForm.no': 'No',
  'logForm.submit': 'Save entry',
  'logForm.failed': 'Failed to save entry.',
  'logForm.missing': 'Feedback form configuration is missing.',

  // Notes and nutrition tabs
  'notes.edit': 'Edit notes',
  'notes.empty': 'No coach notes yet.',
  'notes.add': 'Add notes',
  'notes.title': 'Coach notes',
  'nutrition.edit': 'Edit plan',
  'nutrition.editTitle': 'Edit nutrition plan',
  'nutrition.empty': 'No nutrition plan yet.',
  'nutrition.create': 'Create plan',
  'nutrition.title': 'Nutrition plan',
  'empty.program': 'Program not yet created.',
  'empty.nutrition': 'No nutrition plan available yet.',
  'empty.add-entry': 'Feedback form is not available.',
  'empty.default': 'No data available.',

  // Progress tab
  'progress.empty': 'No measurements yet. Log the first set below to start the charts.',
  'progress.oneSoFar': 'One measurement so far. Add another to see a change.',
  'progress.deltas': '{recent} since {recentDate} · {first} since {firstDate}',
  'progress.logTitle': 'Log measurements',
  'progress.intro': 'Fill in only what was measured. Weight in kg, the rest in cm. The same date replaces that day.',
  'progress.another': 'Another measurement (optional)',
  'progress.anotherPlaceholder': 'e.g. Cadera',
  'progress.value': 'Value (cm)',
  'progress.submit': 'Save measurements',
  'progress.none': 'Enter at least one measurement.',

  // Editor
  'editor.loading': 'Loading…',
  'editor.write': 'Write',
  'editor.preview': 'Preview',
  'editor.markdownLabel': '{title} (Markdown)',
  'editor.discard': 'Discard your unsaved changes?',
  'editor.empty': 'Content cannot be empty.',
  'editor.copyIntro': 'Week {n} starts as a copy of week {from}. Change what should differ, then save.',
  'editor.intro': 'Markdown. Saving replaces the current version.',
  'editor.loadFailed': 'Could not load the editor.',

  // New client
  'newClient.button': '+ Add client',
  'newClient.label': 'Client name',
  'newClient.placeholder': 'e.g. Ana García',
  'newClient.submit': 'Create client',
  'newClient.exists': 'A client with that name already exists.',
  'newClient.failed': 'Could not create the client.',

  // Header account and sign-in
  'account.signOut': 'Sign out',
  'login.tagline': 'Strength for the decades ahead.',
  'login.title': 'Sign in',
  'login.intro': 'Use your LvPrime coach account.',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.showPassword': 'Show password',
  'login.hidePassword': 'Hide password',
  'login.invalidEmail': 'Enter a valid email address.',
  'login.noPassword': 'Enter your password.',
  'login.signingIn': 'Signing in…',
  'login.failed': 'Sign-in failed. Try again.',

  // Coach assistant
  'chat.greeting': "Hi! I'm your fitness coach assistant. Ask me anything about training or nutrition.",
  'chat.error': 'The coach assistant is unavailable right now. Try again.',
  'chat.open': 'Open coach assistant',
  'chat.close': 'Close coach assistant',
  'chat.title': 'Coach assistant',
  'chat.clear': 'Clear chat',
  'chat.closeShort': 'Close',
  'chat.placeholder': 'Ask about training or nutrition...',
  'chat.inputLabel': 'Ask the coach assistant',
  'chat.send': 'Send',
  'chat.thinking': 'Thinking',
  'chat.retry': 'Retry',

  // PDFs
  'pdf.week': 'Week {n}',
  'pdf.progression': 'Progression',
  'pdf.noSchedule': 'No schedule available.',
  'pdf.noDetails': 'No details available.',
  'pdf.nutritionSubtitle': 'Personalized Nutrition Plan',
  'pdf.page': 'Page {i} of {n}',

  // API errors (by the server's error code; English falls back to the server's message)
  'api.unreachable': 'Cannot reach the server. Check your connection and try again.',
  'api.failed': 'Request failed ({status})',
};

export const STRINGS_ES = {
  // App shell (index.html)
  'app.title': 'LvPrime · Espacio del coach',
  'app.logoLabel': 'LvPrime, ir al resumen',
  'app.subtitle': 'Entrenamiento personal · 40+',
  'app.workspace': 'Espacio del coach',
  'app.sidebarLabel': 'Clientes',
  'lang.groupLabel': 'Idioma',
  'lang.es': 'Español',
  'lang.en': 'English',

  // Shared
  'common.allClients': 'Todos los clientes',
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.saving': 'Guardando…',
  'common.date': 'Fecha',
  'common.required': 'obligatorio',
  'common.saved': 'Guardado',
  'common.downloadPdf': 'Descargar PDF',
  'common.pdfFailed': 'No se pudo generar el PDF. Inténtalo de nuevo.',
  'common.refreshFailed': 'Guardado, pero la página no se pudo actualizar. Recarga para verlo.',
  'common.couldNotSave': 'No se pudo guardar. Inténtalo de nuevo.',

  // Status and relative dates
  'status.no-feedback': 'Sin registros',
  'status.needs-checkin': 'Necesita seguimiento',
  'status.on-track': 'Al día',
  'rel.never': 'Nunca',
  'rel.today': 'Hoy',
  'rel.yesterday': 'Ayer',
  'rel.daysAgo': 'hace {n} d',

  // Overview
  'overview.title': 'Clientes',
  'overview.searchPlaceholder': 'Buscar por nombre',
  'overview.searchLabel': 'Buscar clientes',
  'overview.loadFailed': 'No se pudieron cargar los clientes.',
  'overview.empty': 'Agrega tu primer cliente para empezar a armar su programa.',
  'overview.count.one': '{n} cliente',
  'overview.count.other': '{n} clientes',
  'overview.showing': 'Mostrando {visible} de {total} clientes',
  'overview.noFlagged': 'Ningún cliente tiene alertas de dolor o sesiones "brutales" recientes.',
  'overview.noMatch': 'Ningún cliente coincide con "{query}".',
  'overview.noMatchIn': 'Ningún cliente coincide con "{query}" en {filter}.',
  'overview.noneIn': 'Ahora no hay clientes en {filter}.',
  'overview.showAll': 'Mostrar todos los clientes',
  'score.clients': 'Clientes',
  'score.needCheckin': 'Necesitan seguimiento',
  'score.onTrack': 'Al día',
  'score.noFeedback': 'Sin registros aún',
  'filter.groupLabel': 'Filtrar clientes',
  'filter.all': 'Todos',
  'filter.needs-checkin': 'Necesita seguimiento',
  'filter.flagged': 'Con alertas',
  'filter.week-due': 'Toca semana nueva',
  'filter.no-feedback': 'Sin registros aún',
  'filter.archived': 'Archivados',

  // Client card
  'card.pain': 'Dolor {level}/10',
  'card.mentionsPain': 'Menciona dolor',
  'card.brutal': 'Sesión brutal',
  'card.week': 'Semana {n}',
  'card.weekDue': '{week} tiene {days} d · toca semana nueva',
  'card.adherencePercent': '{percent}% hecho · {done}/{total} en {days} d',
  'card.adherenceLogged': '{n} registradas · {days} d',
  'card.adherenceNone': 'Sin sesiones en {days} d',
  'card.programInProgress': 'Programa en curso',
  'card.noProgram': 'Sin programa aún',
  'card.checkIn': 'Último registro: {when}',
  'card.noCheckIn': 'Sin registros aún',
  'card.archived': 'Archivado',

  // Client page
  'customer.loadFailed': 'No se pudo cargar este cliente.',
  'tabs.program': 'Programa',
  'tabs.nutrition': 'Plan de nutrición',
  'tabs.feedback': 'Seguimiento',
  'tabs.progress': 'Progreso',
  'tabs.add-entry': 'Registrar sesión',
  'tabs.notes': 'Notas',
  'difficulty.1': 'Fácil',
  'difficulty.2': 'Moderada',
  'difficulty.3': 'Difícil',
  'difficulty.4': 'Brutal',
  'toast.measurementsSaved': 'Medidas guardadas',
  'toast.feedbackSaved': 'Guardado · ver en Seguimiento',
  'toast.sessionLogged': 'Sesión registrada',
  'hero.lastCheckIn': 'Último registro: {when}',
  'hero.weekOf': 'Semana {current} de {total}',
  'hero.level': 'Nivel',
  'hero.session': 'Sesión',
  'hero.plan': 'Plan',

  // Archive
  'archive.button': 'Archivar cliente',
  'archive.restore': 'Restaurar cliente',
  'archive.confirm': '¿Archivar a {name}? Dejará de aparecer en la lista de clientes y en la barra lateral. Puedes restaurarlo cuando quieras desde el filtro Archivados.',
  'archive.banner': 'Archivado el {date}. Este cliente no aparece en la lista de clientes.',
  'archive.done': 'Cliente archivado',
  'archive.restored': 'Cliente restaurado',
  'archive.failed': 'No se pudo actualizar el cliente. Inténtalo de nuevo.',

  // Attachments
  'attach.title': 'Adjuntos',
  'attach.upload': 'Adjuntar archivo',
  'attach.uploading': 'Subiendo…',
  'attach.uploaded': 'Archivo adjuntado',
  'attach.remove': 'Quitar {name}',
  'attach.confirmRemove': '¿Quitar "{name}"? Esto borra el archivo.',
  'attach.removed': 'Archivo quitado',
  'attach.empty': 'Aún no hay archivos. PDF, imágenes, Word y Excel de hasta {mb} MB.',
  'attach.unavailable': 'Ahora no se pueden cargar los adjuntos.',
  'attach.tooLarge': 'Los archivos deben pesar {mb} MB o menos.',
  'attach.badType': 'Solo se pueden adjuntar PDF, imágenes, texto, Word y Excel.',
  'attach.failed': 'No se pudo subir el archivo. Inténtalo de nuevo.',
  'attach.removeFailed': 'No se pudo quitar el archivo. Inténtalo de nuevo.',

  // Program tab
  'week.navLabel': 'Semana del programa',
  'week.chip': 'Semana {n}',
  'week.lockedTitle': 'Semana pasada (solo lectura)',
  'week.lockedLabel': 'Semana {n}, semana pasada, solo lectura',
  'program.empty': 'Aún no hay programa.',
  'program.createWeek1': 'Crear semana 1',
  'program.week1Title': 'Programa de la semana 1',
  'program.loadWeekFailed': 'No se pudo cargar la semana {n}. Inténtalo de nuevo.',
  'program.editWeek': 'Editar semana',
  'program.editWeekTitle': 'Editar semana {n}',
  'program.newWeek': 'Nueva semana',
  'program.newWeekTitle': 'Nueva semana {n}',
  'program.pastWeek': 'Semana {n} · semana pasada, solo lectura',
  'program.noSchedule': 'No hay rutina para esta semana.',
  'day.navLabel': 'Días del programa',
  'day.watchVideo': '{name}, ver video de demostración',
  'day.rest': 'Descanso {rest}',
  'day.doneToday': 'Hecho hoy',
  'day.doneOn': 'Hecho {date}',
  'day.addDetails': 'Agregar detalles',
  'day.editDetails': 'Editar detalles',
  'day.notes.title': 'Detalles de la sesión',
  'day.notes.hint': 'Una sola nota para toda la sesión. Completa cada ejercicio con tus pesos, repeticiones o cómo te sentiste, y edítala cuando quieras. Puedes guardarla antes de marcar el día como hecho.',
  'day.markDone': 'Marcar como hecho',
  'day.exercises.one': '{n} ejercicio',
  'day.exercises.other': '{n} ejercicios',

  // Feedback tab
  'feedback.trend': 'Tendencia de sesiones',
  'feedback.history': 'Historial de sesiones',
  'feedback.empty': 'Aún no hay sesiones registradas. Registra una sesión para empezar el seguimiento.',
  'stats.completion': 'Cumplimiento',
  'stats.lastSession': 'Última sesión',
  'stats.avgDifficulty': 'Dificultad media',
  'stats.notEnough': 'Aún no hay datos suficientes',
  'entry.undated': 'Sesión sin fecha',
  'entry.completed': 'Completada',
  'entry.notCompleted': 'No completada',
  'entry.felt': 'Sensación',
  'entry.difficulty': 'Dificultad',
  'trend.aria': 'Tendencia de dificultad y cumplimiento por sesión',
  'trend.notEnough': 'Aún no hay suficientes registros para mostrar una tendencia.',
  'trend.unknownDate': 'Fecha desconocida',
  'trend.point': '{date}: {state}, {difficulty}',
  'trend.pointDifficulty': 'dificultad {score}/{max}',
  'trend.noDifficulty': 'sin dificultad registrada',
  'trend.completed': 'Completada',
  'trend.missed': 'No completada',
  'trend.note': 'La altura de la barra muestra la dificultad. Las barras crecen cuando la dificultad se registra como Fácil, Moderada, Difícil o Brutal (o Easy, Moderate, Hard).',

  // Log Session tab
  'logForm.title': 'Registrar una sesión nueva',
  'logForm.intro': 'Solo Completado es obligatorio; deja en blanco lo que no sepas. Las sesiones guardadas aparecen en Seguimiento, de la más reciente a la más antigua.',
  'logForm.label': 'Nombre de la sesión (opcional)',
  'logForm.labelPlaceholder': 'p. ej. Lunes - Piernas A',
  'logForm.select': 'Elegir…',
  'logForm.skip': '—',
  // Labels for the English field names in older feedback.md templates (feedback-fields.js).
  'logField.energy level': 'Nivel de energía',
  'logField.completed': 'Completado',
  'logField.exercises completed': 'Ejercicios completados',
  'logField.how felt': 'Cómo se sintió',
  'logField.how customer felt': 'Cómo se sintió',
  'logField.elbow status': 'Estado del codo',
  'logField.notes': 'Notas',
  'logField.overall impression': 'Impresión general',
  'logForm.yes': 'Sí',
  'logForm.no': 'No',
  'logForm.submit': 'Guardar sesión',
  'logForm.failed': 'No se pudo guardar la sesión.',
  'logForm.missing': 'Falta la configuración del formulario de seguimiento.',

  // Notes and nutrition tabs
  'notes.edit': 'Editar notas',
  'notes.empty': 'Aún no hay notas del coach.',
  'notes.add': 'Agregar notas',
  'notes.title': 'Notas del coach',
  'nutrition.edit': 'Editar plan',
  'nutrition.editTitle': 'Editar plan de nutrición',
  'nutrition.empty': 'Aún no hay plan de nutrición.',
  'nutrition.create': 'Crear plan',
  'nutrition.title': 'Plan de nutrición',
  'empty.program': 'Aún no se ha creado el programa.',
  'empty.nutrition': 'Aún no hay plan de nutrición disponible.',
  'empty.add-entry': 'El formulario de seguimiento no está disponible.',
  'empty.default': 'No hay datos disponibles.',

  // Progress tab
  'progress.empty': 'Aún no hay medidas. Registra las primeras abajo para ver las gráficas.',
  'progress.oneSoFar': 'Una medida hasta ahora. Agrega otra para ver el cambio.',
  'progress.deltas': '{recent} desde {recentDate} · {first} desde {firstDate}',
  'progress.logTitle': 'Registrar medidas',
  'progress.intro': 'Llena solo lo que se midió. Peso en kg, lo demás en cm. La misma fecha reemplaza ese día.',
  'progress.another': 'Otra medida (opcional)',
  'progress.anotherPlaceholder': 'p. ej. Cadera',
  'progress.value': 'Valor (cm)',
  'progress.submit': 'Guardar medidas',
  'progress.none': 'Ingresa al menos una medida.',

  // Editor
  'editor.loading': 'Cargando…',
  'editor.write': 'Escribir',
  'editor.preview': 'Vista previa',
  'editor.markdownLabel': '{title} (Markdown)',
  'editor.discard': '¿Descartar los cambios sin guardar?',
  'editor.empty': 'El contenido no puede estar vacío.',
  'editor.copyIntro': 'La semana {n} empieza como copia de la semana {from}. Cambia lo que deba ser distinto y guarda.',
  'editor.intro': 'Markdown. Al guardar se reemplaza la versión actual.',
  'editor.loadFailed': 'No se pudo abrir el editor.',

  // New client
  'newClient.button': '+ Agregar cliente',
  'newClient.label': 'Nombre del cliente',
  'newClient.placeholder': 'p. ej. Ana García',
  'newClient.submit': 'Crear cliente',
  'newClient.exists': 'Ya existe un cliente con ese nombre.',
  'newClient.failed': 'No se pudo crear el cliente.',

  // Header account and sign-in
  'account.signOut': 'Cerrar sesión',
  'login.tagline': 'Fuerza para las décadas que vienen.',
  'login.title': 'Iniciar sesión',
  'login.intro': 'Usa tu cuenta de coach de LvPrime.',
  'login.email': 'Correo electrónico',
  'login.password': 'Contraseña',
  'login.showPassword': 'Mostrar contraseña',
  'login.hidePassword': 'Ocultar contraseña',
  'login.invalidEmail': 'Ingresa un correo electrónico válido.',
  'login.noPassword': 'Ingresa tu contraseña.',
  'login.signingIn': 'Iniciando sesión…',
  'login.failed': 'No se pudo iniciar sesión. Inténtalo de nuevo.',

  // Coach assistant
  'chat.greeting': '¡Hola! Soy tu asistente de coaching. Pregúntame lo que quieras sobre entrenamiento o nutrición.',
  'chat.error': 'El asistente no está disponible ahora. Inténtalo de nuevo.',
  'chat.open': 'Abrir asistente del coach',
  'chat.close': 'Cerrar asistente del coach',
  'chat.title': 'Asistente del coach',
  'chat.clear': 'Borrar chat',
  'chat.closeShort': 'Cerrar',
  'chat.placeholder': 'Pregunta sobre entrenamiento o nutrición...',
  'chat.inputLabel': 'Pregunta al asistente del coach',
  'chat.send': 'Enviar',
  'chat.thinking': 'Pensando',
  'chat.retry': 'Reintentar',

  // PDFs
  'pdf.week': 'Semana {n}',
  'pdf.progression': 'Progresión',
  'pdf.noSchedule': 'No hay rutina disponible.',
  'pdf.noDetails': 'Sin detalles.',
  'pdf.nutritionSubtitle': 'Plan de nutrición personalizado',
  'pdf.page': 'Página {i} de {n}',

  // API errors (by the server's error code)
  'api.unreachable': 'No se puede conectar con el servidor. Revisa tu conexión e inténtalo de nuevo.',
  'api.failed': 'La solicitud falló ({status})',
  'error.unauthorized': 'Inicia sesión para continuar.',
  'error.invalid_credentials': 'El correo o la contraseña no son correctos.',
  'error.rate_limited': 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
  'error.auth_unavailable': 'El inicio de sesión no está disponible ahora. Inténtalo en un momento.',
  'error.unable_to_load': 'No se pudieron cargar los datos del cliente. Inténtalo de nuevo.',
  'error.customer_not_found': 'No se encontró este cliente.',
  'error.customer_exists': 'Ya existe un cliente con ese nombre.',
  'error.week_locked': 'La semana {weekNumber} está cerrada. Solo se puede editar la semana {currentWeek}.',
  'error.week_number_gap': 'La siguiente semana que puedes agregar es la {expected}.',
  'error.payload_too_large': 'El contenido es demasiado grande.',
  'error.file_too_large': 'Los archivos deben pesar 4 MB o menos.',
  'error.attachment_exists': 'Ya hay un archivo adjunto con ese nombre.',
  'error.archive_unavailable': 'Para archivar clientes hace falta actualizar la base de datos (server/migrations/014-customer-archive.sql).',
  'error.not_found': 'No se encontró.',
};
